<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Service\**" />
    <EmbeddedResource Remove="Service\**" />
    <None Remove="Service\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Ohd.AI.OpenAi.Agents" Version="25.3.4.1904" PrivateAssets="all" />
  </ItemGroup>

  <!--<ItemGroup>
    <PackageReference Include="Ohd.License.Client" Version="25.2.21.1877" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.13" />
    <PackageReference Include="YamlDotNet" Version="16.2.0" />
    <Reference Include="Ohd.AI.Core">
      <HintPath>..\..\..\Ohubev\ohd.agent\Ohd.AI.OpenAi.Agents\bin\Release\net8.0\obf\Ohd.AI.Core.dll</HintPath>
    </Reference>
    <Reference Include="Ohd.AI.OpenAi">
      <HintPath>..\..\..\Ohubev\ohd.agent\Ohd.AI.OpenAi.Agents\bin\Release\net8.0\obf\Ohd.AI.OpenAi.dll</HintPath>
    </Reference>
    <Reference Include="Ohd.AI.OpenAi.Agents">
      <HintPath>..\..\..\Ohubev\ohd.agent\Ohd.AI.OpenAi.Agents\bin\Release\net8.0\obf\Ohd.AI.OpenAi.Agents.dll</HintPath>
    </Reference>
  </ItemGroup>-->


  <ItemGroup>
    <None Update="dev.license.lic">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Supervisor.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="text.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
